# Generated by Django 4.2 on 2024-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='facebook',
            field=models.CharField(default='facebook', max_length=120),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='instagram',
            field=models.CharField(default='instagram', max_length=120),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='linkedin',
            field=models.CharField(default='linkedin', max_length=120),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='twitter',
            field=models.CharField(default='twitter', max_length=120),
        ),
    ]
