# Generated by Django 4.2 on 2024-09-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='ccheduled',
            new_name='scheduled',
        ),
    ]
